// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Ps3ph3VA9xCOBscg1KlnNra4qszTUjc',
    appId: '1:888305859754:web:d901aa71481c38d6ff24d3',
    messagingSenderId: '888305859754',
    projectId: 'fypbee',
    authDomain: 'fypbee.firebaseapp.com',
    storageBucket: 'fypbee.firebasestorage.app',
    measurementId: 'G-JEDCB2FEJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnmxCFS1I0TnTKwmwnLh2G-IIDU8i6CdU',
    appId: '1:888305859754:android:15f6d59043b92685ff24d3',
    messagingSenderId: '888305859754',
    projectId: 'fypbee',
    storageBucket: 'fypbee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxLIX9A0XLGKyxhlvYCVStHFu4ee2Ljd8',
    appId: '1:888305859754:ios:aa20252c72fd985aff24d3',
    messagingSenderId: '888305859754',
    projectId: 'fypbee',
    storageBucket: 'fypbee.firebasestorage.app',
    iosBundleId: 'com.example.fypbee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxLIX9A0XLGKyxhlvYCVStHFu4ee2Ljd8',
    appId: '1:888305859754:ios:aa20252c72fd985aff24d3',
    messagingSenderId: '888305859754',
    projectId: 'fypbee',
    storageBucket: 'fypbee.firebasestorage.app',
    iosBundleId: 'com.example.fypbee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Ps3ph3VA9xCOBscg1KlnNra4qszTUjc',
    appId: '1:888305859754:web:d1b2bb0fc5d3c48cff24d3',
    messagingSenderId: '888305859754',
    projectId: 'fypbee',
    authDomain: 'fypbee.firebaseapp.com',
    storageBucket: 'fypbee.firebasestorage.app',
    measurementId: 'G-GXJ1HTDDR3',
  );
}
